### ISSUE TITLE
iOS Feature

### ISSUE THREAD

**Issue by mahirozdin** [iamalper/flutter_blackhole_vpn#1]
Hi, I'm very impressed about this library! Do you have plans to implement it to iOS or are there any restrictions on iOS side. 
Thanks!

**Comment by iamalper** [comment]
Thanks! I don't have plans for iOS, because i don't have any experience on iOS development and i don't have Mac for Xcode.
This plugin simply uses [VpnService](https://developer.android.com/reference/kotlin/android/net/VpnService). I don't know if similar api exists for iOS.
